// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ProducerInterface is an autogenerated mock type for the ProducerInterface type
type ProducerInterface struct {
	mock.Mock
}

// PublishMessage provides a mock function with given fields: message
func (_m *ProducerInterface) PublishMessage(message string) error {
	ret := _m.Called(message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewProducerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewProducerInterface creates a new instance of ProducerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProducerInterface(t mockConstructorTestingTNewProducerInterface) *ProducerInterface {
	mock := &ProducerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
